Add SQL preprocessor
OCamlPro/superbol-studio-oss pull request #370
Opened 2024-10-14 12:21 UTC by NeoKaios

An up-to-date with master version of #307
Also contains various bugfixes found while launching Gixsql testsuite

2024-10-24 06:44 UTC, nberth commented on test/testsuite/sql/RUN_GIXSQL_TESTS.md
> +Note: mysql tests fails on Linux, it seems to be a case sensitivity issue between Windows and Linux.
```suggestion
Note: mysql tests fail on Linux, it seems to be a case sensitivity issue between Windows and Linux.
```

2024-10-24 07:22 UTC, nberth requested changes
Overall I think we are close to merging this PR; just minor details to address. (I won't review the contents of `sql_preproc` though… wouldn't want to have to edit that code :sweat_smile: ).

2024-10-24 07:22 UTC, nberth commented on src/lsp/sql_preproc/sql_typeck.ml
> +        let size = Cobol_data.Memory.(as_bits field_size / 8) in
Note: there may be some unwanted rounding error hidden here (number of bits here might not be a multiple of 8). Correct code would be:
```suggestion
        let size = (Cobol_data.Memory.as_bits field_size + 7) / 8 in
```

Also `Cobol_data.Memory.NOT_SCALAR` needs to be caught here.

2024-10-24 07:22 UTC, nberth commented on src/lsp/sql_preproc/notes_in_french/know_limitation.md
`known_limitations.md`

2024-10-24 07:22 UTC, nberth commented on src/lsp/sql_preproc/generated_type.ml
Header missing.

2024-10-24 07:22 UTC, nberth commented on src/lsp/sql_preproc/data_gestion.ml
This needs a better name. Probably something like `data_handling`.

2024-10-24 07:22 UTC, nberth commented on src/lsp/sql_preproc/data_gestion.ml
> +let num = ref 0
:crying_cat_face:

2024-10-24 07:22 UTC, nberth commented on src/lsp/sql_preproc/data_gestion.ml
> +            var_importance = "02";
I guess `var_importance` should be called `var_level` instead.

2024-10-24 07:22 UTC, nberth commented on src/lsp/sql_ast/visitor.ml
Please break the long lines.

2024-10-24 14:57 UTC, GitMensch commented on test/testsuite/sql/RUN_GIXSQL_TESTS.md
> +[This issue](https://github.com/OCamlPro/superbol-studio-oss/issues/371) explains that in more details.
Maybe that issue should also be referenced in the extension README concerning the status of the EXEC SQL support (note: there definitely should be an update to both README and CHANGELOG concerning this PR!)

2024-10-25 11:17 UTC, nberth commented on src/lsp/sql_preproc/known_limitation.md
> +Good luck!
That's a funny diff ;-)

2025-01-08 08:35 UTC, GitMensch commented
Friendly ping - What is the current state of this PR?
While I mostly wait for #375, getting this in would be a good step forward.

2025-03-17 06:59 UTC, GitMensch commented
@nberth wrote nearly 5 months ago:

> Overall I think we are close to merging this PR; just minor details to address.

... so I wonder if those details are now addressed / this PR can get in (possibly with a final polish)

2025-05-23 07:16 UTC, nberth approved these changes

2025-05-23 07:29 UTC, merged